// Seletor de parcelas compacto e parcelas em “A receber”.
import * as L from './lib.js';

L.run(async ({page}) => {
  await L.signup(page);
  await L.addCard(page, 'Inter', 5000, 5, 12);
  let d = await L.db(page);
  const card = d.cards[0];

  L.section('Seletor compacto no formulário da aba');
  await L.tab(page, 'lancamentos');
  L.ok(await page.$('select#txInstall') === null && await page.$('#txInstallField .stepper') !== null, 'lista de 24 opções trocada pelo seletor − / +');
  await L.setVal(page, '#txPayment', 'card:' + card.id);
  L.ok(!(await page.$eval('#txInstallField', el => el.hidden)), 'aparece ao escolher o cartão');
  L.ok(await L.text(page, '#txInstallHint') === 'À vista', 'começa à vista');
  await page.type('#txAmount', '1000');
  for (let i = 0; i < 3; i++) await page.click('#txInstallField [data-step="1"]');
  L.ok(await page.$eval('#txInstall', el => el.value) === '4', '+ três vezes vai para 4x');
  L.ok(/4x de R\$\s?250,00 · total R\$\s?1\.000,00/.test(await L.text(page, '#txInstallHint')), 'mostra valor da parcela e total');
  await page.click('#txInstallField [data-step="-1"]');
  L.ok(/^3x de R\$\s?333,33 · total R\$\s?1\.000,00$/.test(await L.text(page, '#txInstallHint')), 'resumo curto com parcela e total');
  await L.setVal(page, '#txInstall', '99');
  L.ok(await page.$eval('#txInstall', el => el.value) === '24', 'limite de 24 parcelas');
  await L.setVal(page, '#txInstall', '0');
  L.ok(await page.$eval('#txInstall', el => el.value) === '1', 'mínimo de 1 parcela');
  for (let i = 0; i < 30; i++) await page.click('#txInstallField [data-step="1"]');
  L.ok(await page.$eval('#txInstall', el => el.value) === '24', '+ não passa de 24');
  await L.setVal(page, '#txInstall', '3');
  await L.setVal(page, '#txCategory', 'compras');
  await page.type('#txDesc', 'Geladeira');
  await page.click('#txForm button[type=submit]'); await L.sleep(300);
  d = await L.db(page);
  const geladeira = d.transactions.filter(t => t.installment && t.installment.baseDescription === 'Geladeira');
  L.ok(geladeira.length === 3, 'compra salva em 3 parcelas');
  L.ok(geladeira.map(t => t.amount).sort().join(',') === '333.33,333.33,333.34', 'centavos que sobram ficam em uma parcela (333,34)');
  L.ok(await page.$eval('#txInstall', el => el.value) === '1', 'seletor volta para 1 depois de salvar');
  await L.setVal(page, '#txInstall', '5');
  await L.setVal(page, '#txPayment', 'conta');
  L.ok(await page.$eval('#txInstall', el => el.value) === '1' && await page.$eval('#txInstallField', el => el.hidden), 'trocar para Pix zera e esconde as parcelas');

  L.section('Seletor compacto no popup do +');
  await page.click('#fabAdd'); await L.sleep(150);
  await L.setVal(page, '#mAmount', '90');
  await L.setVal(page, '#mPay', 'card:' + card.id);
  await page.click('#mInstallField [data-step="1"]');
  L.ok(/2x de R\$\s?45,00/.test(await L.text(page, '#mInstallHint')), 'popup mostra 2x de R$ 45,00');
  await L.submitModal(page);
  d = await L.db(page);
  L.ok(d.transactions.filter(t => t.installment && t.installment.total === 2).length === 2, 'popup salvou 2 parcelas');

  L.section('A receber parcelado (valor total)');
  await L.tab(page, 'receber');
  L.ok(await page.$eval('#recvModeField', el => el.hidden), 'opção total/parcela escondida à vista');
  await page.type('#recvPerson', 'Maria');
  await page.type('#recvTotal', '600');
  await page.click('#recvForm [data-for="recvInstall"][data-step="1"]');
  await page.click('#recvForm [data-for="recvInstall"][data-step="1"]');
  L.ok(!(await page.$eval('#recvModeField', el => el.hidden)), 'parcelado mostra “o total / de cada parcela”');
  L.ok(await L.text(page, '#recvTotalLabel') === 'Valor total' && await L.text(page, '#recvDueLabel') === '1ª parcela em', 'rótulos mudam para parcelado');
  L.ok(/3x de R\$\s?200,00 · total R\$\s?600,00/.test(await L.text(page, '#recvInstallHint')), 'resumo 3x de R$ 200,00');
  const first = L.dayOffset(0);
  await L.setVal(page, '#recvDue', first);
  await page.click('#recvForm button[type=submit]'); await L.sleep(250);
  d = await L.db(page);
  let maria = d.receivables.find(r => r.person === 'Maria');
  L.ok(maria && maria.installments === 3 && maria.installmentAmount === 200 && maria.totalAmount === 600, 'salvo com 3 parcelas de 200');
  L.ok(await page.$eval('#recvInstall', el => el.value) === '1' && await page.$eval('#recvModeField', el => el.hidden), 'formulário volta ao normal depois de salvar');
  let cardTxt = await L.text(page, '#recvGrid');
  L.ok(/Parcela 1 de 3 · R\$\s?200,00 · vence/.test(cardTxt) && cardTxt.includes(L.br(first)), 'card mostra parcela 1 de 3 e o vencimento');
  L.ok(/· 3x/.test(cardTxt), 'etiqueta mostra 3x');

  L.section('Registrar recebimento: valor da parcela ou outro valor');
  await page.click('[data-recv-get="' + maria.id + '"]'); await L.sleep(150);
  L.ok(/Valor da parcela \(R\$\s?200,00\)/.test(await L.text(page, '#modalRoot')), 'oferece o valor da parcela');
  L.ok(await page.$eval('#rcvOtherField', el => el.hidden), 'campo de outro valor escondido');
  await L.submitModal(page);
  d = await L.db(page);
  maria = d.receivables.find(r => r.id === maria.id);
  L.ok(maria.receivedAmount === 200, 'registrou 200');
  L.ok(d.transactions.some(t => t.type === 'income' && t.amount === 200 && /Maria/.test(t.description)), 'lançou o ganho');
  cardTxt = await L.text(page, '#recvGrid');
  L.ok(/Parcela 2 de 3/.test(cardTxt) && cardTxt.includes(L.br(L.plusMonths(first, 1))), 'passou para a parcela 2 com vencimento no mês seguinte');
  await page.click('[data-recv-get="' + maria.id + '"]'); await L.sleep(150);
  await page.click('input[name=mode][value=outro]'); await L.sleep(80);
  L.ok(!(await page.$eval('#rcvOtherField', el => el.hidden)), '“Outro valor” mostra o campo');
  await page.type('#rcvOther', '500');
  await L.submitModal(page);
  L.ok(/não pode passar de R\$\s?400,00/.test(await L.modalError(page)), 'recusa valor maior que o restante');
  await page.$eval('#rcvOther', el => { el.value = ''; });
  await page.type('#rcvOther', '50');
  await page.click('#modalRoot input[name=extra]');
  await L.submitModal(page);
  d = await L.db(page);
  maria = d.receivables.find(r => r.id === maria.id);
  L.ok(maria.receivedAmount === 250, 'outro valor somou 50');
  L.ok(!d.transactions.some(t => t.type === 'income' && t.amount === 50), 'sem ganho quando desmarcado');
  L.ok(/Parcela 2 de 3/.test(await L.text(page, '#recvGrid')), 'valor parcial não pula a parcela');

  L.section('Cobrar parcela');
  await page.click('[data-recv-charge="' + maria.id + '"]'); await L.sleep(150);
  const msg = await page.$eval('#chargeMsg', el => el.value);
  L.ok(/parcela 2 de 3, de R\$\s?200,00/.test(msg) && msg.includes(L.br(L.plusMonths(first, 1))), 'mensagem cita a parcela e o vencimento');
  await L.closeModal(page);

  L.section('A receber parcelado (valor de cada parcela) e atraso');
  await page.type('#recvPerson', 'João');
  await page.type('#recvTotal', '150');
  await L.setVal(page, '#recvInstall', '4');
  await page.click('input[name=recvMode][value=parcela]');
  L.ok(await L.text(page, '#recvTotalLabel') === 'Valor de cada parcela', 'rótulo vira “Valor de cada parcela”');
  L.ok(/4x de R\$\s?150,00 · total R\$\s?600,00/.test(await L.text(page, '#recvInstallHint')), 'resumo calcula o total');
  await L.setVal(page, '#recvDue', L.plusMonths(first, -2));
  await page.click('#recvForm button[type=submit]'); await L.sleep(250);
  d = await L.db(page);
  const joao = d.receivables.find(r => r.person === 'João');
  L.ok(joao.totalAmount === 600 && joao.installmentAmount === 150, 'total 600 e parcela 150');
  L.ok(/atrasado/.test(await page.$eval('[data-recv-get="' + joao.id + '"]', el => el.closest('.debt-card').textContent)), 'parcela vencida aparece como atrasada');

  L.section('Compra no meu cartão lançada na fatura');
  await L.setVal(page, '#recvKind', 'cartao');
  L.ok(!(await page.$eval('#recvCardField', el => el.hidden)) && !(await page.$eval('#recvLaunchField', el => el.hidden)), 'mostra o cartão e a opção de lançar');
  await page.type('#recvPerson', 'Ana');
  await page.type('#recvTotal', '300');
  await L.setVal(page, '#recvInstall', '3');
  await page.click('#recvLaunch');
  await page.click('#recvForm button[type=submit]'); await L.sleep(300);
  d = await L.db(page);
  const ana = d.receivables.find(r => r.person === 'Ana');
  const anaTx = d.transactions.filter(t => t.installment && t.installment.baseDescription === 'Compra para Ana');
  L.ok(anaTx.length === 3 && anaTx.every(t => t.cardId === card.id && t.amount === 100 && t.category === 'compras'), 'compra entrou no cartão em 3x de 100');
  L.ok(ana.cardId === card.id && ana.installments === 3 && !!ana.dueDate, 'a receber ligado ao cartão, com vencimento da fatura');
  L.ok(/entrou na fatura do Inter/.test(await L.allToasts(page)), 'toast avisa da fatura');
  L.ok(await page.$eval('#recvCardField', el => el.hidden), 'campos do cartão somem depois de salvar');

  L.section('“Paguei por outra pessoa” parcelado vira a receber parcelado');
  await L.tab(page, 'lancamentos');
  await page.type('#txAmount', '400');
  await L.setVal(page, '#txPayment', 'card:' + card.id);
  await L.setVal(page, '#txInstall', '4');
  await page.click('#txForOther');
  await page.type('#txOtherName', 'Pedro');
  await page.click('#txForm button[type=submit]'); await L.sleep(300);
  d = await L.db(page);
  const pedro = d.receivables.find(r => r.person === 'Pedro');
  L.ok(pedro && pedro.installments === 4 && pedro.installmentAmount === 100 && pedro.totalAmount === 400 && !!pedro.dueDate, 'a receber de Pedro em 4x de 100 com vencimento');

  L.section('Celular');
  await page.setViewport({width: 375, height: 800});
  await L.tab(page, 'receber');
  await page.type('#recvTotal', '10');
  await L.setVal(page, '#recvInstall', '2');
  L.ok(await L.noHorizontalScroll(page), 'A receber cabe na tela com as opções de parcela');
  await L.tab(page, 'lancamentos');
  L.ok(await L.noHorizontalScroll(page), 'Ganhos e gastos cabe na tela');
});
