// Previsões recolhidas no card de novo lançamento, termo da pesquisa e transições.
import * as L from './lib.js';

L.run(async ({page}) => {
  L.section('Termo da pesquisa no cadastro');
  await page.goto(L.BASE, {waitUntil: 'domcontentloaded'});
  await page.evaluate(() => { localStorage.clear(); localStorage.setItem('granaleve_backend', 'local'); });
  await page.reload({waitUntil: 'domcontentloaded'});
  await page.click('[data-action="go-signup"]');
  L.ok(!(await page.$eval('#signupResearch', el => el.checked)), 'participar da pesquisa começa desmarcado (opt-in)');
  L.ok(/18 anos ou mais/.test(await L.text(page, '.research-optin')), 'pede 18 anos ou mais');
  L.ok(await page.$eval('#signupResearchProfile', el => el.hidden), 'perfil opcional só aparece ao aceitar');
  await page.click('#signupForm [data-info="pesquisa"]'); await L.sleep(150);
  L.ok(await L.modalTitle(page) === 'Termo de consentimento da pesquisa', 'link abre o termo');
  const term = await L.text(page, '#modalRoot');
  L.ok(/O que nunca é coletado/.test(term) && /Valores, descrições/.test(term) && /art\. 7º, I/.test(term) && /não envia nenhum dado/.test(term), 'termo diz o que não é coletado, a base legal e que nada é enviado nesta versão');
  await L.closeModal(page);
  await page.click('#signupResearch');
  L.ok(!(await page.$eval('#signupResearchProfile', el => el.hidden)), 'aceitar mostra faixa etária e estado');
  L.ok(await page.$$eval('#signupAge option', os => os.map(o => o.value)).then(v => v[0] === '' && !v.includes('15-17')), 'faixas etárias começam em 18 e há “Prefiro não dizer”');
  await L.setVal(page, '#signupAge', '18-24');
  await L.setVal(page, '#signupUf', 'PR');
  const email = 'pesq' + Date.now() + '@teste.com';
  await page.evaluate((key) => localStorage.setItem('granaleve_prefs_' + key, JSON.stringify({quickEntryOff: true})), email);
  await page.type('#signupName', 'Bia'); await page.type('#signupEmail', email); await page.type('#signupPassword', 'senha123');
  await page.click('#signupStorageOk');
  await page.click('#signupForm button[type=submit]');
  await page.waitForSelector('#viewApp:not([hidden])'); await L.sleep(300);
  const profile = await page.evaluate((key) => JSON.parse(localStorage.getItem('granaleve_local_db_v1')).users[key].profile, email);
  L.ok(profile.research && profile.research.consent === true && profile.research.version === '2' && /^\d{4}-\d{2}-\d{2}T/.test(profile.research.at), 'consentimento salvo com versão e data');
  L.ok(profile.research.ageRange === '18-24' && profile.research.uf === 'PR', 'perfil opcional salvo');

  L.section('Sair e voltar ao estudo em “Seus dados”');
  await page.click('#storageBtn'); await L.sleep(150);
  L.ok(/Você participa do estudo desde/.test(await L.text(page, '#researchStatus')), 'mostra que participa');
  await page.click('#modalRoot [data-research]'); await L.sleep(200);
  L.ok(await L.modalTitle(page) === 'Sair do estudo?', 'abre a confirmação de saída');
  await L.submitModal(page); await L.sleep(150);
  let p = await page.evaluate((key) => JSON.parse(localStorage.getItem('granaleve_local_db_v1')).users[key].profile.research, email);
  L.ok(p.consent === false && !p.ageRange, 'saiu do estudo e o perfil opcional foi apagado');
  await page.click('#storageBtn'); await L.sleep(150);
  L.ok(/não participa/.test(await L.text(page, '#researchStatus')), 'status atualizado');
  await page.click('#modalRoot [data-research]'); await L.sleep(200);
  await L.submitModal(page);
  L.ok(/18 anos ou mais e aceita/.test(await L.modalError(page)), 'para participar precisa marcar o aceite');
  await page.click('#modalRoot input[name=accept]');
  await L.submitModal(page); await L.sleep(150);
  p = await page.evaluate((key) => JSON.parse(localStorage.getItem('granaleve_local_db_v1')).users[key].profile.research, email);
  L.ok(p.consent === true, 'voltou a participar');

  L.section('Previsões recolhidas no card de novo lançamento');
  await L.tab(page, 'lancamentos');
  L.ok(await page.$eval('#forecastPanel', el => el.hidden) && await page.$eval('#forecastToggle', el => el.getAttribute('aria-expanded')) === 'false', 'previsões começam recolhidas');
  L.ok(await page.$eval('#forecastPanel', el => !!el.closest('.card') && el.closest('.card').querySelector('h3').textContent === 'Novo lançamento'), 'ficam dentro do card de novo lançamento');
  L.ok(await page.$eval('#forecastCount', el => el.hidden), 'sem previsões, sem contador');
  await page.click('#forecastToggle'); await L.sleep(80);
  L.ok(!(await page.$eval('#forecastPanel', el => el.hidden)) && await page.evaluate(() => document.activeElement.id) === 'fcDesc', 'ícone abre o painel com foco na descrição');
  await page.type('#fcDesc', 'Salário'); await page.type('#fcAmount', '3000');
  await page.click('#forecastForm button[type=submit]'); await L.sleep(200);
  L.ok(!(await page.$eval('#forecastPanel', el => el.hidden)), 'painel continua aberto depois de adicionar');
  L.ok(await page.$eval('#forecastCount', el => !el.hidden && el.textContent === '1'), 'contador mostra 1 previsão pendente');
  L.ok(/^Previstas\s*1 a receber$/.test(await L.text(page, '#forecastToggle')), 'leitor de tela ouve “Previstas 1 a receber”');
  await page.click('[data-fc-receive]'); await L.sleep(150);
  await L.submitModal(page);
  L.ok(await page.$eval('#forecastCount', el => el.hidden), 'depois de “Recebi”, contador some');
  await page.click('#forecastToggle'); await L.sleep(80);
  L.ok(await page.$eval('#forecastPanel', el => el.hidden), 'ícone fecha o painel');

  L.section('Transições ao trocar de área');
  await page.emulateMediaFeatures([{name: 'prefers-reduced-motion', value: 'no-preference'}]);
  await L.tab(page, 'metas');
  L.ok(await page.$eval('#tab-metas', el => getComputedStyle(el).animationName) === 'panelIn', 'área nova entra com animação');
  await page.click('#fabAdd'); await L.sleep(50);
  L.ok(await page.$eval('#modalRoot .modal', el => getComputedStyle(el).animationName) === 'modalIn', 'popup abre com animação');
  await L.closeModal(page);
  await page.emulateMediaFeatures([{name: 'prefers-reduced-motion', value: 'reduce'}]);
  await L.tab(page, 'dashboard');
  L.ok(await page.$eval('#tab-dashboard', el => getComputedStyle(el).animationName) === 'none', 'quem pede menos movimento não vê animação');
});
